dist: bionic
branches:
  except:
    - gh-pages
language: perl6
sudo: required
perl6:
  - latest
before_install:
  - sudo apt update
  - sudo apt install libgdbm-dev
install:
  - rakudobrew build-zef
  - zef --deps-only install .
  - zef build .
