dist: xenial
branches:
  except:
    - gh-pages
language: perl6
sudo: required
perl6:
  - latest
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgdbm3
  - sudo apt-get install -y libgdbm-dev
install:
  - rakudobrew build-zef
  - zef --/test --deps-only install .
  - zef build .
